name = "ihut-shop"
compatibility_date = "2024-05-02"
compatibility_flags = ["nodejs_compat"]

[vars]
# You can define your environment variables here if required.
# Note: For production secrets and keys (like NEXT_PUBLIC_SUPABASE_URL), 
# it is best practice to configure them in the Cloudflare Pages Dashboard settings.
